#!/bin/bash
# ══════════════════════════════════════════════════════════════
#  NodeBlast — generate js/firebase-config.local.js from env vars
#
#  Local dev:  populate .env, then run `bash scripts/build-firebase-config.sh`
#  Vercel:     runs automatically via the buildCommand in vercel.json,
#              sourcing variables set in the Vercel project dashboard.
# ══════════════════════════════════════════════════════════════

set -e

# Load .env for local runs. On Vercel the env vars are already in the
# process environment, so sourcing is harmless if .env doesn't exist.
if [ -f .env ]; then
  set -a
  # shellcheck source=/dev/null
  . ./.env
  set +a
fi

required_vars=(
  FIREBASE_API_KEY_PROD FIREBASE_AUTH_DOMAIN_PROD FIREBASE_PROJECT_ID_PROD
  FIREBASE_STORAGE_BUCKET_PROD FIREBASE_MESSAGING_SENDER_ID_PROD FIREBASE_APP_ID_PROD
  FIREBASE_API_KEY_DEV FIREBASE_AUTH_DOMAIN_DEV FIREBASE_PROJECT_ID_DEV
  FIREBASE_STORAGE_BUCKET_DEV FIREBASE_MESSAGING_SENDER_ID_DEV FIREBASE_APP_ID_DEV
)
missing=()
for v in "${required_vars[@]}"; do
  if [ -z "${!v}" ]; then missing+=("$v"); fi
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "build-firebase-config.sh: missing required env vars:" >&2
  printf '  - %s\n' "${missing[@]}" >&2
  exit 1
fi

cat > js/firebase-config.local.js <<EOF
// Generated by scripts/build-firebase-config.sh — DO NOT COMMIT.
export const prodConfig = {
  apiKey:            "${FIREBASE_API_KEY_PROD}",
  authDomain:        "${FIREBASE_AUTH_DOMAIN_PROD}",
  databaseURL:       "${FIREBASE_DATABASE_URL_PROD}",
  projectId:         "${FIREBASE_PROJECT_ID_PROD}",
  storageBucket:     "${FIREBASE_STORAGE_BUCKET_PROD}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID_PROD}",
  appId:             "${FIREBASE_APP_ID_PROD}",
  measurementId:     "${FIREBASE_MEASUREMENT_ID_PROD}"
};

export const devConfig = {
  apiKey:            "${FIREBASE_API_KEY_DEV}",
  authDomain:        "${FIREBASE_AUTH_DOMAIN_DEV}",
  databaseURL:       "${FIREBASE_DATABASE_URL_DEV}",
  projectId:         "${FIREBASE_PROJECT_ID_DEV}",
  storageBucket:     "${FIREBASE_STORAGE_BUCKET_DEV}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID_DEV}",
  appId:             "${FIREBASE_APP_ID_DEV}",
  measurementId:     "${FIREBASE_MEASUREMENT_ID_DEV}"
};
EOF

echo "Wrote js/firebase-config.local.js"
